### ISSUE TITLE
Development setup for frontend is not there

### ISSUE THREAD

**Issue by kamalkoranga** [mahmoudessam820/dev-valley#5]

**Comment by mahmoudessam820** [comment]
Hi, @Kamalkoranga 

Ok, I will review and merge the request :)

**Comment by mahmoudessam820** [comment]
Hi, @Kamalkoranga 

- I see there this configuration file for the TypeScript compiler.
- I did not use TypeScript before and I want to work with you on the front end, Why do we need to use TypeScript?
- Please let me know what tools you will work with to be able to work with you.

I'm waiting for you.

Thank you.

**Comment by kamalkoranga** [comment]
Okay, I will remove it :)

**Comment by mahmoudessam820** [comment]
Take your time :)

**Comment by kamalkoranga** [comment]
have you initialized frontend by this -> `npm init vue@latest`  or any other?

**Comment by mahmoudessam820** [comment]
- No, I'm not working on the front end yet, I just install the basic libraries for the front end.
- Now I working just on the backend.
-  I want to use Vue.js and  Axios.
- You can see in the package.json => dependencies you will find what the packages install until now.

**Comment by kamalkoranga** [comment]
Okay, but the frontend is not working... since I'm using Node 18.

**Comment by kamalkoranga** [comment]
> * No, I'm not working on the front end yet, I just install the basic libraries for the front end.
> * Now I working just on the backend.
> * I want to use Vue.js and  Axios.
> * You can see in the package.json => dependencies you will find what the packages install until now.

So, I think `npm init vue@latest` would be enough for this project. What do you think?

**Comment by mahmoudessam820** [comment]
> Okay, but the frontend is not working... since I'm using Node 18.

My Node -v is v16.13.1

- I guess because I'm not working on the front end until now I can update my Node -v to 18 and let you prepare the frontend setup and after that, I can fetch the frontend setup you made.

- I guess we have to update the readme file to mention what node.js -v we use.

**Comment by mahmoudessam820** [comment]
> > * No, I'm not working on the front end yet, I just install the basic libraries for the front end.
> > * Now I working just on the backend.
> > * I want to use Vue.js and  Axios.
> > * You can see in the package.json => dependencies you will find what the packages install until now.
> 
> So, I think `npm init vue@latest` would be enough for this project. What do you think?

I agree with you.

**Comment by kamalkoranga** [comment]
Okay :)
